version: 1

run:
  timeout: 5m
  build-tags:
    - integration
    - examples

linters:
  enable-all: false
  enable:
    - errcheck
    - staticcheck

linters-settings:
  errcheck:
    exclude:
      - os.Setenv
      - os.Unsetenv
      - fmt.Fprint
      - fmt.Fprintf
      - io.Closer.Close

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: .*\.go
      linters:
        - staticcheck
      text: "should omit type .* from declaration"
    - path: .*\.go
      linters:
        - staticcheck
      text: "could use tagged switch on"
